### ISSUE TITLE
Demo the user experience

### ISSUE THREAD

**Issue by vjrantal** [vjrantal/account-linking-demo-bot#1]

**Comment by vjrantal** [comment]
![account-linking-iphone](https://cloud.githubusercontent.com/assets/207474/20264373/dde1a2d8-aa73-11e6-8dfa-b2f4b4352105.gif)

**Comment by cAstraea** [comment]
how would this work with facebook social login ? Do I need another endpoint from express + passport facebook strategy ?

**Comment by vjrantal** [comment]
@cAstraea Replied to you at http://blog.vjrantal.net/2016/11/15/facebook-account-linking-with-microsoft-bot-framework/#comment-3206764333 .
