### ISSUE TITLE
c# linking

### ISSUE THREAD

**Issue by ghost** [vjrantal/account-linking-demo-bot#2]
is it possible to link my bot with facebook using this solution with c# ?

**Comment by vjrantal** [comment]
@lonche You could implement the same authentication flow by using the Microsoft Bot Framework C# SDK. I didn't right now find a ready example that would do it, but you should be able to follow the approach implemented in this repository on Node.js and reimplement the same in C#.

**Comment by vjrantal** [comment]
@lonche Hoping I was able to respond to your question.
